export default {
  login: 'asmirpljakic',
  id: 92116999,
  node_id: 'U_kgDOBX2YBw',
  avatar_url: 'https://avatars.githubusercontent.com/u/92116999?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/asmirpljakic',
  html_url: 'https://github.com/asmirpljakic',
  followers_url: 'https://api.github.com/users/asmirpljakic/followers',
  following_url:
    'https://api.github.com/users/asmirpljakic/following{/other_user}',
  gists_url: 'https://api.github.com/users/asmirpljakic/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/asmirpljakic/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/asmirpljakic/subscriptions',
  organizations_url: 'https://api.github.com/users/asmirpljakic/orgs',
  repos_url: 'https://api.github.com/users/asmirpljakic/repos',
  events_url: 'https://api.github.com/users/asmirpljakic/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/asmirpljakic/received_events',
  type: 'User',
  site_admin: false,
  name: 'Asmir Pljakic',
  company: null,
  blog: '',
  location: 'Novi Pazar, Serbia',
  email: null,
  hireable: null,
  bio: "I'm a mission driven full stack web developer. Currently based in Serbia.",
  twitter_username: null,
  public_repos: 35,
  public_gists: 13,
  followers: 748,
  following: 6,
  created_at: '2021-10-07T18:03:24Z',
  updated_at: '2023-04-27T07:31:37Z',
};
